# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcaApp.Category')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcaApp.Classification')),
            ],
        ),
    ]
